### ISSUE TITLE
Introduce encodeNulls in YamlConfiguration

### ISSUE THREAD

**Issue by bkenn** [charleskorn/kaml#50] opened 2020-09-30 06:09 UTC
As seem in https://github.com/Kotlin/kotlinx.serialization/issues/195, I would like to ignore nulls but keep defaults. My use case is creating some kubernetes objects in Kotlin. The nulls clutter up the file. Not sure about the scope of this. I have just been introduced to this project.

**Comment by charleskorn** [comment] 2020-09-30 06:23
Hi @bkenn, thanks for the request. This seems to be a duplicate of #8. As explained there, supporting this would require changes in kotlinx.serialization first, so I'd suggest adding your support to the issue you linked to above.

**Comment by bkenn** [comment] 2020-09-30 14:24
Thanks for the quick reply. I will be doing that.

**Comment by charleskorn** [comment] 2021-04-25 00:11
Closing due to inactivity.

**Closed by charleskorn** 2021-04-25 00:11 UTC
Labels: enhancement, state:blocked
